// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/api/v1/transactions/admin": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Admin transactions"
                ],
                "summary": "List all member transactions",
                "parameters": [
                    {
                        "type": "string",
                        "format": "uuid",
                        "description": "Member UUID",
                        "name": "memberId",
                        "in": "query"
                    },
                    {
                        "minimum": 1,
                        "type": "integer",
                        "default": 1,
                        "description": "Page number",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "maximum": 100,
                        "minimum": 1,
                        "type": "integer",
                        "default": 20,
                        "description": "Page size",
                        "name": "pageSize",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/response.PageSuccess"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/response.ErrorResponse"
                        }
                    },
                    "403": {
                        "description": "Forbidden",
                        "schema": {
                            "$ref": "#/definitions/response.ErrorResponse"
                        }
                    },
                    "422": {
                        "description": "Unprocessable Entity",
                        "schema": {
                            "$ref": "#/definitions/response.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/transactions/admin/loans/{loanId}/return": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Admin transactions"
                ],
                "summary": "Return any member loan",
                "parameters": [
                    {
                        "type": "string",
                        "format": "uuid",
                        "description": "Loan UUID",
                        "name": "loanId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Book stock update confirmed",
                        "schema": {
                            "$ref": "#/definitions/response.LoanSuccess"
                        }
                    },
                    "202": {
                        "description": "Return committed; stock acknowledgement pending",
                        "schema": {
                            "$ref": "#/definitions/response.LoanSuccess"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/response.ErrorResponse"
                        }
                    },
                    "403": {
                        "description": "Forbidden",
                        "schema": {
                            "$ref": "#/definitions/response.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/response.ErrorResponse"
                        }
                    },
                    "422": {
                        "description": "Unprocessable Entity",
                        "schema": {
                            "$ref": "#/definitions/response.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/transactions/loans": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Transactions"
                ],
                "summary": "Borrow book",
                "parameters": [
                    {
                        "description": "Book to borrow",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/request.Borrow"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/response.LoanSuccess"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/response.ErrorResponse"
                        }
                    },
                    "403": {
                        "description": "Forbidden",
                        "schema": {
                            "$ref": "#/definitions/response.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/response.ErrorResponse"
                        }
                    },
                    "409": {
                        "description": "Conflict",
                        "schema": {
                            "$ref": "#/definitions/response.ErrorResponse"
                        }
                    },
                    "422": {
                        "description": "Unprocessable Entity",
                        "schema": {
                            "$ref": "#/definitions/response.ErrorResponse"
                        }
                    },
                    "503": {
                        "description": "Service Unavailable",
                        "schema": {
                            "$ref": "#/definitions/response.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/transactions/loans/{loanId}/return": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Transactions"
                ],
                "summary": "Quote own loan return",
                "parameters": [
                    {
                        "type": "string",
                        "format": "uuid",
                        "description": "Loan UUID",
                        "name": "loanId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/response.ReturnQuoteSuccess"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/response.ErrorResponse"
                        }
                    },
                    "403": {
                        "description": "Forbidden",
                        "schema": {
                            "$ref": "#/definitions/response.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/response.ErrorResponse"
                        }
                    },
                    "422": {
                        "description": "Unprocessable Entity",
                        "schema": {
                            "$ref": "#/definitions/response.ErrorResponse"
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Transactions"
                ],
                "summary": "Return own loan",
                "parameters": [
                    {
                        "type": "string",
                        "format": "uuid",
                        "description": "Loan UUID",
                        "name": "loanId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Accepted fine quote",
                        "name": "request",
                        "in": "body",
                        "schema": {
                            "$ref": "#/definitions/request.Return"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Book stock update confirmed",
                        "schema": {
                            "$ref": "#/definitions/response.LoanSuccess"
                        }
                    },
                    "202": {
                        "description": "Return committed; stock acknowledgement pending",
                        "schema": {
                            "$ref": "#/definitions/response.LoanSuccess"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/response.ErrorResponse"
                        }
                    },
                    "403": {
                        "description": "Forbidden",
                        "schema": {
                            "$ref": "#/definitions/response.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/response.ErrorResponse"
                        }
                    },
                    "409": {
                        "description": "Conflict",
                        "schema": {
                            "$ref": "#/definitions/response.ErrorResponse"
                        }
                    },
                    "422": {
                        "description": "Unprocessable Entity",
                        "schema": {
                            "$ref": "#/definitions/response.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/transactions/me": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Transactions"
                ],
                "summary": "List own transaction history",
                "parameters": [
                    {
                        "minimum": 1,
                        "type": "integer",
                        "default": 1,
                        "description": "Page number",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "maximum": 100,
                        "minimum": 1,
                        "type": "integer",
                        "default": 20,
                        "description": "Page size",
                        "name": "pageSize",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/response.PageSuccess"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/response.ErrorResponse"
                        }
                    },
                    "403": {
                        "description": "Forbidden",
                        "schema": {
                            "$ref": "#/definitions/response.ErrorResponse"
                        }
                    },
                    "422": {
                        "description": "Unprocessable Entity",
                        "schema": {
                            "$ref": "#/definitions/response.ErrorResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "entity.Fine": {
            "type": "object",
            "properties": {
                "assessedAt": {
                    "type": "string"
                },
                "currency": {
                    "type": "string"
                },
                "dailyRateMinor": {
                    "type": "integer"
                },
                "id": {
                    "type": "string"
                },
                "loanId": {
                    "type": "string"
                },
                "memberId": {
                    "type": "string"
                },
                "overdueDays": {
                    "type": "integer"
                },
                "status": {
                    "$ref": "#/definitions/entity.FineStatus"
                },
                "totalAmountMinor": {
                    "type": "integer"
                }
            }
        },
        "entity.FineQuote": {
            "type": "object",
            "properties": {
                "currency": {
                    "type": "string"
                },
                "dailyRateMinor": {
                    "type": "integer"
                },
                "overdueDays": {
                    "type": "integer"
                },
                "totalAmountMinor": {
                    "type": "integer"
                }
            }
        },
        "entity.FineStatus": {
            "type": "string",
            "enum": [
                "unpaid"
            ],
            "x-enum-varnames": [
                "FineUnpaid"
            ]
        },
        "entity.Loan": {
            "type": "object",
            "properties": {
                "bookId": {
                    "type": "string"
                },
                "borrowedAt": {
                    "type": "string"
                },
                "createdAt": {
                    "type": "string"
                },
                "dueAt": {
                    "type": "string"
                },
                "fine": {
                    "$ref": "#/definitions/entity.Fine"
                },
                "id": {
                    "type": "string"
                },
                "memberId": {
                    "type": "string"
                },
                "returnedAt": {
                    "type": "string"
                },
                "status": {
                    "$ref": "#/definitions/entity.LoanStatus"
                },
                "stockSyncStatus": {
                    "$ref": "#/definitions/entity.StockSyncStatus"
                },
                "updatedAt": {
                    "type": "string"
                }
            }
        },
        "entity.LoanStatus": {
            "type": "string",
            "enum": [
                "pending_reservation",
                "active",
                "returned",
                "cancelled"
            ],
            "x-enum-varnames": [
                "LoanPendingReservation",
                "LoanActive",
                "LoanReturned",
                "LoanCancelled"
            ]
        },
        "entity.ReturnQuote": {
            "type": "object",
            "properties": {
                "bookId": {
                    "type": "string"
                },
                "dueAt": {
                    "type": "string"
                },
                "fine": {
                    "$ref": "#/definitions/entity.FineQuote"
                },
                "loanId": {
                    "type": "string"
                },
                "quotedAt": {
                    "type": "string"
                }
            }
        },
        "entity.StockSyncStatus": {
            "type": "string",
            "enum": [
                "not_applicable",
                "pending",
                "confirmed"
            ],
            "x-enum-varnames": [
                "StockSyncNotApplicable",
                "StockSyncPending",
                "StockSyncConfirmed"
            ]
        },
        "entity.Transaction": {
            "type": "object",
            "properties": {
                "bookId": {
                    "type": "string"
                },
                "fine": {
                    "$ref": "#/definitions/entity.Fine"
                },
                "id": {
                    "type": "string"
                },
                "loanId": {
                    "type": "string"
                },
                "memberId": {
                    "type": "string"
                },
                "occurredAt": {
                    "type": "string"
                },
                "type": {
                    "$ref": "#/definitions/entity.TransactionType"
                }
            }
        },
        "entity.TransactionType": {
            "type": "string",
            "enum": [
                "borrow",
                "return"
            ],
            "x-enum-varnames": [
                "TransactionBorrow",
                "TransactionReturn"
            ]
        },
        "request.Borrow": {
            "type": "object",
            "required": [
                "bookId"
            ],
            "properties": {
                "bookId": {
                    "type": "string"
                }
            }
        },
        "request.Return": {
            "type": "object",
            "properties": {
                "acceptedFineAmountMinor": {
                    "type": "integer",
                    "minimum": 0
                }
            }
        },
        "response.ErrorResponse": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "string"
                },
                "data": {},
                "message": {
                    "type": "string"
                }
            }
        },
        "response.LoanSuccess": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "string",
                    "example": "LMS-200000"
                },
                "data": {
                    "$ref": "#/definitions/entity.Loan"
                }
            }
        },
        "response.PageSuccess": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "string",
                    "example": "LMS-200000"
                },
                "data": {
                    "$ref": "#/definitions/transaction.Page"
                }
            }
        },
        "response.ReturnQuoteSuccess": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "string",
                    "example": "LMS-200000"
                },
                "data": {
                    "$ref": "#/definitions/entity.ReturnQuote"
                }
            }
        },
        "transaction.Page": {
            "type": "object",
            "properties": {
                "items": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/entity.Transaction"
                    }
                },
                "page": {
                    "type": "integer"
                },
                "pageSize": {
                    "type": "integer"
                },
                "totalItems": {
                    "type": "integer"
                },
                "totalPages": {
                    "type": "integer"
                }
            }
        }
    },
    "securityDefinitions": {
        "BearerAuth": {
            "description": "Prefix access tokens with \"Bearer \".",
            "type": "apiKey",
            "name": "Authorization",
            "in": "header"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "",
	BasePath:         "/",
	Schemes:          []string{"http", "https"},
	Title:            "Library Management Transaction API",
	Description:      "Loan, return, fine assessment, and transaction-history service.\nKong authenticates human tokens; this service rechecks trusted identity headers and endpoint scopes.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
